- name: NAS playbook
  hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/host.yml
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/scripts.yml
    - import_tasks: tasks/comms.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/web.yml
    - import_tasks: tasks/stats.yml
    - import_tasks: tasks/storage.yml
