- name: Add primary repository
  apt_repository:
    repo: deb {{ debian_repo_base }} {{ debian_version }} main contrib
    filename: main

- name: Install packages
  apt:
    update_cache: yes
    name:
    - zfsutils-linux
    - btrfs-progs
    - postfix
    - bsd-mailx # mail executable
    - libsasl2-modules # postfix SASL authentication
    - nginx
    - zsh
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - wget
    - vim
    - htop
    - strace
    - zstd
    - wireguard
    - pv
    - tshark
    - netplan.io
    - certbot
    - python3-certbot-dns-cloudflare
    - hdparm
    - jq
    - hddtemp
    - lm-sensors
    - sqlite3
    - chrony

- block:
  - name: Pull armored APT GPG keys
    get_url:
      url: "{{ item.value.gpg }}"
      dest: "/etc/apt/{{ item.key }}.armor.gpg"
      force: yes
    loop: "{{ apt_gpg_keys.armor | dict2items }}"
    register: apt_gpg_keys_armor_reg

  - name: Install armored APT GPG keys
    command: "gpg --dearmor --yes -o {{ trusted_gpg_d }}/{{ item.key }}.gpg /etc/apt/{{ item.key }}.armor.gpg"
    loop: "{{ apt_gpg_keys.armor | dict2items }}"
    when: apt_gpg_keys_armor_reg.changed

  - name: Install binary APT GPG keys
    get_url:
      url: "{{ item.value.gpg }}"
      dest: "{{ trusted_gpg_d }}/{{ item.key }}.gpg"
      force: yes
    loop: "{{ apt_gpg_keys.binary | dict2items }}"

  - name: Add signed repositories
    apt_repository:
      repo: deb [arch=amd64 signed-by={{ trusted_gpg_d }}/{{ item.key }}.gpg] {{ item.value.repo }}
      filename: "{{ item.key }}"
    loop: "{{ apt_gpg_keys.armor | combine(apt_gpg_keys.binary) | dict2items }}"

  vars:
    trusted_gpg_d: /etc/apt/trusted.gpg.d

- name: Install additional packages
  apt:
    update_cache: yes
    name:
      - docker-ce
      - influxdb2
      - telegraf

- name: Perform safe upgrade
  apt:
    upgrade: safe
