- name: Add primary repository
  apt_repository:
    repo: deb {{ debian_repo_base }} {{ debian_version }} main contrib
    filename: main

- name: Install packages
  apt:
    update_cache: yes
    name:
    - zfsutils-linux
    - postfix
    - bsd-mailx # mail executable
    - libsasl2-modules # postfix SASL authentication
    - nginx
    - zsh
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - wget
    - vim
    - htop
    - zstd
    - wireguard
    - pv
    - tshark
    - netplan.io
    - certbot
    - python3-certbot-dns-cloudflare
    - hdparm
    - jq
    - hddtemp
    - lm-sensors

- block:
  - name: Install armored APT GPG keys
    shell: |
      curl -fsSL {{ item.value.gpg }} | gpg --yes --dearmor -o {{ trusted_gpg_d }}/{{ item.key }}.gpg
    loop: "{{ apt_gpg_keys.armor | dict2items }}"
    args:
      warn: false

  - name: Install binary APT GPG keys
    get_url:
      url: "{{ item.value.gpg }}"
      dest: "{{ trusted_gpg_d }}/{{ item.key }}.gpg"
    loop: "{{ apt_gpg_keys.binary | dict2items }}"

  - name: Add signed repositories
    apt_repository:
      repo: deb [arch=amd64 signed-by={{ trusted_gpg_d }}/{{ item.key }}.gpg] {{ item.value.repo }}
      filename: "{{ item.key }}"
    loop: "{{ apt_gpg_keys.armor | combine(apt_gpg_keys.binary) | dict2items }}"

  - name: Install additional packages
    apt:
      update_cache: yes
      name:
        - docker-ce
        - influxdb2
        - telegraf

  vars:
    trusted_gpg_d: /etc/apt/trusted.gpg.d

- name: Perform safe upgrade
  apt:
    upgrade: safe
