- name: Configure postfix
  template:
    src: "{{ item }}"
    dest: /etc/postfix
  with_fileglob: "templates/postfix/*"
  notify:
    - Restart postfix

- name: Ensure postfix runs
  systemd:
    name: postfix
    enabled: yes
    state: started
