- name: Configure Docker
  template:
    src: docker/daemon.json
    dest: /etc/docker
  notify:
    - Reload docker

- name: Start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create compose stack directories
  file:
    path: "{{ ssd_storage.root }}/docker/{{ item }}"
    state: directory
  loop: "{{ docker.stacks }}"

- name: Update compose stacks
  template:
    src: docker/docker-compose/{{ item }}.yml
    dest: "{{ ssd_storage.root }}/docker/{{ item }}/docker-compose.yml"
  loop: "{{ docker.stacks }}"
  notify:
    - Upgrade docker stacks
