
- name: Configure Docker
  template:
    src: docker/daemon.json
    dest: /etc/docker
  notify:
    - Reload docker

- name: Start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- block:
  - name: Create Docker plugin directory
    file:
      path: "{{ plugin_dir }}"
      state: directory

  - name: Install docker-compose plugin
    get_url:
      url: https://github.com/docker/compose-cli/releases/download/{{ docker.compose_version }}/docker-compose-linux-amd64
      dest: "{{ plugin_dir }}/docker-compose"
      mode: 0755

  vars:
    plugin_dir: /root/.docker/cli-plugins

- name: Create compose stack directories
  file:
    path: "{{ ssd_storage.root }}/docker/{{ item }}"
    state: directory
  loop: "{{ docker.stacks }}"

- name: Update compose stacks
  template:
    src: docker/docker-compose/{{ item }}.yml
    dest: "{{ ssd_storage.root }}/docker/{{ item }}/docker-compose.yml"
  loop: "{{ docker.stacks }}"
  notify:
    - Upgrade docker stacks
