- block:
  - name: Check for Docker compose V2
    stat:
      path: "{{ plugin_dir }}/docker-compose"
    register: stat_result

  - name: Install Docker compose V2
    shell: |
      mkdir -p {{ plugin_dir }}
      curl -SL https://github.com/docker/compose-cli/releases/download/v2.0.0-rc.1/docker-compose-linux-amd64 -o {{ plugin_dir }}/docker-compose
      chmod +x {{ plugin_dir }}/docker-compose
    args:
      warn: false
    when: not stat_result.stat.exists

  vars:
    plugin_dir: /root/.docker/cli-plugins

- name: Create compose stack directories
  file:
    path: "{{ conf_directory }}/docker/{{ item }}"
    state: directory
  loop: "{{ docker_stacks }}"

- name: Update compose stacks
  template:
    src: docker/docker-compose/{{ item }}.yml
    dest: "{{ conf_directory }}/docker/{{ item }}/docker-compose.yml" 
  loop: "{{ docker_stacks }}"

- name: Add unprivileged user to Docker group
  user:
    name: "{{ unprivileged_user_name }}"
    groups:
      - docker
    append: yes

- block:
  - name: Configure Docker
    template:
      src: docker/daemon.json
      dest: /etc/docker
    register: daemon_json

  - name: Restart Docker
    service:
      name: docker
      state: restarted
    when: daemon_json.changed
