- name: Set hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Set default configuration
  template:
    src: "{{ item }}"
    dest: /etc/default
  with_fileglob: "templates/default/*"

- block:
  - name: Set NTP servers
    template:
      src: chrony_sources.j2
      dest: /etc/chrony/sources.d/nas.sources
    register: chrony_src

  - name: Reload chrony sources
    command: chronyc reload sources
    when: chrony_src.changed

- block:
  - name: Check legacy network conf
    stat:
      path: "{{ legacy_conf_path }}"
    register: legacy_conf

  - name: Backup legacy network conf
    copy:
      src: "{{ legacy_conf_path }}"
      dest: "{{ legacy_conf_path }}.bak"
      mode: preserve
    when: legacy_conf.stat.exists

  - name: Remove legacy network conf
    file:
      path: "{{ legacy_conf_path }}"
      state: absent

  - name: Install netplan conf
    template:
      src: netplan/{{ network.netplan }}
      dest: /etc/netplan
    register: netplan_conf

  - name: Enable networkd
    systemd:
      name: systemd-networkd
      enabled: yes
      state: started

  - name: Apply netplan
    command: netplan apply
    when: netplan_conf.changed

  when: network.managed and local_run is not defined
  vars:
    legacy_conf_path: /etc/network/interfaces

- name: Configure host SSH
  template:
    src: "{{ item }}"
    dest: /etc/ssh
  with_fileglob: "templates/ssh/host/*"
  register: ssh_config

- name: Reload SSH
  systemd:
    name: ssh
    state: reloaded
  when: ssh_config.changed

- name: Create root SSH directory
  file:
    path: /root/.ssh
    mode: 0700
    state: directory

- name: Install root SSH authorized_keys
  template:
    src: ssh/user/authorized_keys
    dest: /root/.ssh

- name: Create unprivileged user SSH directory
  file:
    path: "{{ unprivileged_user_reg.home }}/.ssh"
    mode: 0700
    owner: "{{ unprivileged_user.name }}"
    group: "{{ unprivileged_user.group }}"
    state: directory

- name: Install unprivileged user SSH authorized_keys
  template:
    src: ssh/user/authorized_keys
    dest: "{{ unprivileged_user_reg.home }}/.ssh"
