- name: Set hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Set default configuration
  template:
    src: "{{ item }}"
    dest: /etc/default
  with_fileglob: "templates/default/*"
  notify:
    - Changed /etc/defaults

- name: Set NTP servers
  template:
    src: chrony_sources.j2
    dest: /etc/chrony/sources.d/nas.sources
  notify:
    - Reload chrony sources

- block:
  - name: Check legacy network conf
    stat:
      path: "{{ legacy_conf_path }}"
    register: legacy_conf

  - name: Backup legacy network conf
    copy:
      src: "{{ legacy_conf_path }}"
      dest: "{{ legacy_conf_path }}.bak"
      remote_src: yes
      mode: preserve
    when: legacy_conf.stat.exists

  - name: Remove legacy network conf
    file:
      path: "{{ legacy_conf_path }}"
      state: absent

  - name: Install netplan conf
    template:
      src: network/{{ network.netplan }}
      dest: /etc/netplan
    register: netplan_conf

  - name: Configure resolv.conf
    template:
      src: network/resolv.conf
      dest: /etc

  - name: Enable networkd
    systemd:
      name: systemd-networkd
      enabled: yes
      state: started

  - name: Apply netplan
    command: netplan apply
    when: netplan_conf.changed

  when: manage_network
  vars:
    legacy_conf_path: /etc/network/interfaces

- name: Set MOTD
  template:
    src: "motd"
    dest: /etc

- name: Configure host SSH
  template:
    src: "{{ item }}"
    dest: /etc/ssh
  with_fileglob: "templates/ssh/host/*"
  notify:
    - Reload SSH

- name: Create root SSH directory
  file:
    path: /root/.ssh
    mode: 0700
    state: directory

- name: Install root SSH authorized_keys
  template:
    src: ssh/user/authorized_keys
    dest: /root/.ssh

- name: Create unprivileged user SSH directory
  file:
    path: "{{ unprivileged_user_reg.home }}/.ssh"
    mode: 0700
    owner: "{{ unprivileged_user.name }}"
    group: "{{ unprivileged_user.group }}"
    state: directory

- name: Install unprivileged user SSH authorized_keys
  template:
    src: ssh/user/authorized_keys
    dest: "{{ unprivileged_user_reg.home }}/.ssh"

- block:
  - name: Check root SSH keypair
    stat:
      path: "{{ priv_key }}"
    register: root_priv_key_reg

  - name: Generate root SSH keypair
    command: ssh-keygen -t {{ ssh.root_key.algo }} -f {{ priv_key }} -N ""
    when: not root_priv_key_reg.stat.exists

  - name: Register root SSH pubkey
    command: cat {{ priv_key }}.pub
    changed_when: false
    when: not root_priv_key_reg.stat.exists
    register: root_pub_key

  - name: Output root SSH pubkey
    debug:
      msg:
        - New SSH keypair was generated. Install it where applicable.
        - IPv4 proxy SSL sync will not work until you install it there.
        - "{{ root_pub_key.stdout }}"
    when: '"stdout" in root_pub_key'

  vars:
    priv_key: /root/.ssh/id_{{ ssh.root_key.algo }}

- name: Create private directory
  file:
    path: "{{ private_dir }}"
    state: directory

- name: Install private files
  template:
    src: "{{ item }}"
    dest: "{{ private_dir }}"
  with_fileglob: "templates/private/*"

- name: Install kernel EFI post-install hook
  copy:
    src: files/systemdboot/zz_copy_efi
    dest: /etc/kernel/postinst.d
    mode: 0755
  when: use_systemdboot
  notify:
    - Run kernel EFI post-install hook
