- block:
  - name: Test for Oh My ZSH installation
    stat:
      path: /root/.oh-my-zsh
    register: stat_result

  - name: Install Oh My ZSH for root
    shell: |
      curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
    args:
      warn: false
    when: not stat_result.stat.exists

- name: Configure root ZSH
  copy:
    src: "{{ item }}"
    dest: /root
  with_fileglob: "files/zsh/.*"

- name: Create root bin directory
  file:
    path: /root/bin
    state: directory

- name: Install root scripts
  template:
    src: "{{ item }}"
    dest: /root/bin
    mode: 0755
  with_fileglob: "templates/scripts/*"

- name: Create private directory
  file:
    path: "{{ conf_directory }}/private"
    state: directory

- name: Install private files
  template:
    src: "{{ item }}"
    dest: "{{ conf_directory }}/private"
  with_fileglob: "templates/private/*"

- name: Install Bitwarden backup crontab
  cron:
    name: Backup Bitwarden state
    hour: "5"
    minute: "0"
    job: /root/bin/bitwarden_backup.sh

- name: Install systemd services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system
  with_fileglob: "templates/systemd/*.service"

- name: Restart systemd services
  systemd:
    name: "{{ item | basename }}"
    enabled: yes
    state: restarted
  with_fileglob: "templates/systemd/*.service"
