- name: Create root fish config directories
  file:
    path: /root/.config/fish/functions
    state: directory

- name: Configure root fish shell
  copy:
    src: "{{ item }}"
    dest: /root/.config/fish
  with_fileglob: "files/fish/*"

- name: Install fisher
  get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: /root/.config/fish/functions/fisher.fish
  notify: Update fisher plugins

- name: Configure fisher plugins
  copy:
    content: "{{ fisher_plugins | join('\n') }}\n"
    dest: /root/.config/fish/fish_plugins
  notify: Update fisher plugins

- name: Create root bin directory
  file:
    path: /root/bin
    state: directory

- name: Install root scripts
  template:
    src: "{{ item }}"
    dest: /root/bin
    mode: 0755
  with_fileglob: "templates/scripts/*"

- name: Install global scripts
  template:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 0755
  with_fileglob: "templates/bin/*"

- name: Install Bitwarden backup crontab
  cron:
    name: Backup Bitwarden state
    hour: "5"
    minute: "0"
    job: /root/bin/bitwarden_backup.sh

- name: Install configarr crontab
  cron:
    name: Run configarr
    hour: "4"
    minute: "0"
    job: "cd {{ ssd_storage.root }}/docker/main && docker compose run --rm configarr"

- name: Install systemd services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system
  with_fileglob: "templates/systemd/*.service"
  register: systemd_services_reg
  notify:
    - Reload systemd
    - Restart custom systemd services

- name: Install network links
  template:
    src: "{{ item }}"
    dest: /etc/systemd/network
  with_fileglob: "templates/systemd/network/*.link"
