- name: Add Netdata user to Docker group
  user:
    name: netdata
    groups:
      - docker
    append: yes

- name: Configure Netdata
  template:
    src: "{{ item }}"
    dest: /etc/netdata
  with_fileglob: "templates/netdata/*"
  register: netdata_conf_reg

- name: Configure Netdata python modules
  template:
    src: "{{ item }}"
    dest: /etc/netdata/python.d
  with_fileglob: "templates/netdata/python.d/*"
  register: netdata_python_conf_reg

- name: Restart Netdata
  systemd:
    name: netdata
    state: restarted
  when: netdata_conf_reg.changed or netdata_python_conf_reg.changed

- name: Configure Prometheus
  template:
    src: "{{ item }}"
    dest: /etc/prometheus
  with_fileglob: "templates/prometheus/*"
  register: prometheus_conf_reg

- name: Create Prometheus TSDB directory
  file:
    path: "{{ prometheus.storage_path }}"
    owner: prometheus
    group: prometheus
    state: directory
  register: prometheus_tsdb_reg

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
  when: etc_defaults.changed or prometheus_conf_reg.changed or prometheus_tsdb_reg.changed
