- name: Add Netdata user to Docker group
  user:
    name: netdata
    groups:
      - docker
    append: yes

- name: Configure Netdata
  template:
    src: "{{ item }}"
    dest: /etc/netdata
  with_fileglob: "templates/netdata/*"
  notify:
    - Restart netdata

- name: Configure Netdata python modules
  template:
    src: "{{ item }}"
    dest: /etc/netdata/python.d
  with_fileglob: "templates/netdata/python.d/*"
  notify:
    - Restart netdata

- name: Configure Prometheus
  template:
    src: "{{ item }}"
    dest: /etc/prometheus
  with_fileglob: "templates/prometheus/*"
  notify:
    - Restart prometheus

- name: Create Prometheus TSDB directory
  file:
    path: "{{ prometheus.storage_path }}"
    owner: prometheus
    group: prometheus
    state: directory
  notify:
    - Restart prometheus
