- block:
  - name: Check for LE conf for {{ hostname }}
    stat:
      path: /etc/letsencrypt/renewal/{{ hostname }}.conf
    register: le_conf

  - name: Configure LE cert for {{ hostname }}
    shell: |
      certbot certonly {{ certbot_flags | default(omit) }} -n \
      -d {{ hostname }} -d "*.{{ hostname }}" \
      --agree-tos --email {{ emails.dawn }} \
      --post-hook /root/bin/cert_postrenew.sh \
      --dns-cloudflare --dns-cloudflare-credentials {{ conf_directory }}/private/cloudflare_dawnflash.cz.ini
    when: not le_conf.stat.exists
