- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Reload SSH
  systemd:
    name: ssh
    state: reloaded

- name: Reload docker
  systemd:
    name: docker
    state: reloaded

- name: Restart postfix
  systemd:
    name: postfix
    state: restarted

- name: Restart netdata
  systemd:
    name: netdata
    state: restarted

- name: Restart prometheus
  systemd:
    name: prometheus
    state: restarted
  listen: Changed /etc/defaults

- name: Restart custom systemd services
  systemd:
    name: "{{ item | basename }}"
    enabled: yes
    state: restarted
  loop: "{{ systemd_services_reg.results | selectattr('changed', 'equalto', True) | map(attribute='item') }}"

- name: Run kernel EFI post-install hook
  shell: /etc/kernel/postinst.d/zz_copy_efi "$(uname -r)"

- name: Reload chrony sources
  command: chronyc reload sources

- name: Upgrade docker stacks
  command: /root/bin/docker_upgrade.sh
  when: manage_containers
